### ISSUE TITLE
Some rules should be silent

### ISSUE THREAD

**Issue by torkleyy** [Ristarg/ronfmt#1]
I think a couple of rules should be silent, like so:

```
// implicit
WHITESPACE = _{ " " | "\n" | "\t" | "\r" }
COMMENT = _{ line_comment | block_comment }
line_comment = { "//" ~ line_comment_inner ~ (NEWLINE | &EOI) }
line_comment_inner = { (!NEWLINE ~ ANY)* }
block_comment = { "/*" ~ (block_comment | block_comment_inner)  ~ "*/" }
block_comment_inner = { (!"*/" ~ ANY)* }

// booleans
bool = { "true" | "false" }

// numbers
sign = { "+" | "-" }

signed_int = @{ sign? ~ unsigned_int }
unsigned_int = { with_base | ASCII_DIGIT+ }
with_base = { "0" ~ ("x" | "b" | "o") ~ ASCII_HEX_DIGIT+ }

float = @{ float_std | float_frac }
float_std = { sign? ~ ASCII_DIGIT+ ~ "." ~ ASCII_DIGIT* ~ float_exp? }
float_frac = { "." ~ ASCII_DIGIT+ ~ float_exp? }
float_exp = { ("e" | "E") ~ ASCII_DIGIT+ }

// chars
char = ${ "'" ~ char_inner ~ "'" }
char_inner = { "\\'" | (!"'" ~ ANY)* }

// strings
string = ${ string_std | string_raw }
string_std = _{ "\"" ~ string_std_inner ~ "\"" }
string_std_inner = _{ ("\\\"" | !"\"" ~ ANY)* }
string_raw = _{
    "r" ~ PUSH("#"*) ~ "\"" ~
    string_raw_inner ~
    "\"" ~ POP
}
string_raw_inner = _{ (!("\"" ~ PEEK) ~ ANY)* }

// collections
comma_separated_values = _{ value ~ ("," ~ value)* ~ ","? }
list = { "[" ~ comma_separated_values? ~ "]" }
tuple = { "(" ~ comma_separated_values? ~ ")" }

map = { "{" ~ map_inner? ~ "}" }
map_inner = _{ map_entry ~ ("," ~ map_entry)* ~ ","? }
map_entry = { value ~ ":" ~ value }

// types
fields = { field ~ ("," ~ field)* ~ ","? }
field = { ident ~ ":" ~ value }
ident = @{ (ASCII_ALPHA | "_") ~ (ASCII_ALPHANUMERIC | "_")* }

named_type = { anonymous_type_fields | named_type_fields | named_type_tuple | named_type_unit }
anonymous_type_fields = _{ "(" ~ fields? ~ ")" }
named_type_fields = _{ ident ~ "(" ~ fields? ~ ")" }
named_type_tuple = _{ ident ~ tuple }
named_type_unit = _{ ident }

value = { float | signed_int | bool | char | string | tuple | list | map | named_type }

extension = {
    "#" ~ "!" ~ "[" ~ "enable" ~ "(" ~
    ident ~ ("," ~ ident)* ~ ","? ~
    ")" ~ "]"
}

ron_file = { SOI ~ extension* ~ value ~ EOI }
```

I'm considering to reuse this grammar in RON, so if we can find a pest file that works for both, that would be great.

**Comment by torkleyy** [comment]
Also, I noticed an issue with error reporting (possibly not something that can be fixed in the grammar):

```
r#"a"
```

gives

```
 --> 1:2
  |
1 | r#"a"
  |  ^---
  |
  = expected EOI or tuple
```

**Comment by Ristarg** [comment]
For reporting: it's all done internally in pest, so I'm not sure if I can do anything about it, but I'll look into it. Although even if it can't be fixed, pointing out the place where error occurs is already pretty good.

For silent rules: as far as I understand, any rule that is used inside of an atomic rule `@` is treated as silent, and any rule that is used inside of a compound atomic `$` is treated as atomic `@`, so those additional silents would be redundant.

This grammar is still in a bit of a flux, as I'm having some trouble figuring out how to best handle comments, but about reusing it for RON: I've done a bit of thinking about it and I think it might be better not to directly reuse it. For the purposes of formatting, it is beneficial to be able to parse some illegal sequences (e.g. `0b01abc` is not a legal integer, but we would handle it as normal), to allow parsing and formatting as much RON as possible. Perhaps it would be a better choice to use this grammar as a base, and adjust it to closely mirror the actual parsing done by the `ron` crate? That would probably serve as a more useful specification for alternative implementations, as opposed to formatting tools.

**Comment by torkleyy** [comment]
Okay, makes sense.
As for silent rules, I experimented on pest.rs and my changes made some superfluous tokens disappear. I don't know why it produced those initially.

**Comment by Ristarg** [comment]
I'm going to consider this issue resolved.
